name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: run vet
        run: go vet ./...
      - name: build all packages
        run: go build ./...
      - name: check for vulnerabilities
        run: go tool govulncheck ./...
      - name: Run tests
        run: go test -vet=off --cover ./...
